import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Slider from "../components/slider";
import Banner from "@/components/banner";
import Search from "@/components/search";
import VendorList from "@/components/vendorList";
import Teams from "@/components/teams";

// import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
      </Head>
      <Banner />
      <Search />
      <VendorList />
      <Teams />

      {/* <Header /> */}
      <div>{/* <Slider /> */}</div>
    </>
  );
}
